# These files are created over the course of testing, and will be copied locally at the end
dir: /home/iped/logs/{0.label}

# Each log name should match a program and command below
#
# Each log has the following optional fields:
#   dir: sub-directory
#   log: substituted in command, required if specified below
#   out: redirects stdout to this file
#   err: redirects stderr to this file
# Available variables:
#   {i}: Index of command instance if command is repeated.
#        If not used, repeated instances of the command will overwrite the file
pcap_encoder:
    out: encoder.out
    err: encoder.err
pcap_dropper:
    out: dropper.out
    err: dropper.err
pcap_decoder:
    out: decoder.out
    err: decoder.err
p4_encoder:
    dir: encoder
    out: output.txt
    err: err.txt
p4_decoder:
    dir: decoder
    out: output.txt
    err: err.txt
p4_dropper:
    dir: dropper
    out: output.txt
    err: err.txt
tcpdump_in:
    dir: tcpdump_in
    log: tcpdump_{i}.pcap
    out: tcpdump_{i}.out
    err: tcpdump_{i}.err
tcpdump_out:
    dir: tcpdump_out
    log: tcpdump_{i}.pcap
    out: tcpdump_{i}.out
    err: tcpdump_{i}.err
tcpreplay:
    out: tcpreplay.out
    err: tcpreplay.err
enable_fec:
    out: enable_fec.out
    err: enable_fec.err
