########
## The remote executables available to the tool
########

# Each program can be referenced from a "command"

# Each program has the following required fields:
#   host: Address of machine on which to execute the command
#         (should reference {0.hosts.<host>})
#   start: Command used to start the program
#
# The following optional fields:
#   stop: Command used to stop execution of the program
#         (used only if 'duration' is present in the command arguments)
#   fg: If present and true, command is run in foreground and blocks execution
#
# And has access to the following variables:
#   {log}: Expanded location of the log (including path) if defined in logs above
#   {var}: Where `var` is a field defined in the 'commands' section below
#

tcpdump_in:
    host: all
    start: '{0.dirs.bin}/tcpdump -Q in -XX -i {0.IFACE} -w {log}'
    stop: pkill -f tcpdump

tcpdump_out:
    host: all
    start: '{0.dirs.bin}/tcpdump -Q out -XX -i {0.IFACE} -w {log}'
    stop: pkill -f tcpdump

kill_all:
    host: all
    start: "pkill -f simple_switch; pkill -f tcpdump"

p4_encoder:
    host: encoder
    start: >-
        {0.dirs.bmv2}/targets/booster_switch/simple_switch
        -i 1@{0.IFACE}
        --thrift-port 9091
        --device-id 1
        --nanolog ipc:///tmp/bm-0-log.ipc
        {0.dirs.p4_json}/Encoder.json
        --log-console

p4_dropper:
    host: dropper
    start: >-
        {0.dirs.bmv2}/targets/booster_switch/simple_switch
        -i 1@{0.IFACE}
        --thrift-port 9091
        --device-id 1
        --nanolog ipc:///tmp/bm-0-log.ipc
        {0.dirs.p4_json}/Dropper.json
        --log-console

p4_decoder:
    host: decoder
    start: >-
        {0.dirs.bmv2}/targets/booster_switch/simple_switch
        -i 1@{0.IFACE}
        --thrift-port 9091
        --device-id 1
        --nanolog ipc:///tmp/bm-0-log.ipc
        {0.dirs.p4_json}/Decoder.json
        --log-console

enable_fec:
    host: sender
    start: '{0.dirs.bin}/tcpreplay -i {0.IFACE} {0.dirs.p4_json}/../../lldp_enable_fec.pcap'
    fg: true
    check_rtn: 0

pcap_encoder:
    host: encoder
    start: '{0.dirs.fecBoosters}/fecEncodeBooster -i {0.IFACE} -r {0.dirs.fecBoosters}/tag_all.txt'
    stop: pkill -f fecEncodeBooster

pcap_dropper:
    host: dropper
    start: '{0.dirs.fecBoosters}/forwardingNonbooster -i {0.IFACE}'
    stop: pkill -f forwardingNonbooster

pcap_decoder:
    host: decoder
    start: '{0.dirs.fecBoosters}/fecDecodeBooster -i {0.IFACE} -r {0.dirs.fecBoosters}/tag_all.txt'
    stop: pkill -f fecDecodeBooster

tcpreplay:
    host: sender
    start: '~/bin/tcpreplay -i {0.IFACE} {input}'
    fg: true
