# Each host has the following required fields:
#   addr: URL or IP by which the tool connects to the machine
all:
    - addr: tclust1
    - addr: tclust2
    - addr: tclust3
    - addr: tclust4
    - addr: tclust5
sender:
    addr: tclust1
encoder:
    addr: tclust2
dropper:
    addr: tclust3
decoder:
    addr: tclust4
receiver:
    addr: tclust5
